language: c
sudo: true
addons:
  apt:
    packages:
    - pandoc
    - pandoc-citeproc
before_install: 
install: 
script:
- pandoc -N --variable mainfont="Lato" --variable sansfont="Lato" --variable monofont="Roboto"
  --variable fontsize=12pt --variable version=1.17.2 D2.3-UF.md  --toc -o D2.3-UF.odt
notifications:
  slack:
    secure: QlPjUp23r/sTjgfcWE6lHStwAErL3qC49i7RKUGcVHT1JPR2Dd86ePPYRynGdmIZaB0uhDFX9p7FMuGJycWvkqd36whebdkCF2v+wbD4UCaP9Qs6/OTsc1oKafjmA2ZbWm/dHEYhXBf8pNToD9STyfhgLE5/ILFoOriIXUZ5u/OplWLPFIKmdef4kvYNTvSpK4wyboDvXpR4Dv8XG8r8s2IegDaSuS/kGlQd+LEJH0Jmbhoeqid1jRI5iwjFTqtiSvfAm39NomBSwstQHCUczB/sG+tKXXG/qvt2prhdM7uWTUxoQghbhD0bAvF1sYpl/YTqQXnFhp0aV9l70brWd0zDX9N0UhZYVPCWKrFUlW4zLctti1wErFisUUc5UM7+cEhlO8vWsHSWs2k00YxKY7JXUb01ucENwKNk31jLatvX0BgFaNYHydV2q/ZXs3Go7Hvr9j+x0E4jhp/k6W/3E3npHmota/0wF+25JeoN9BSH2y4VHb5rROIxX9qNAvms5FDBV8QV+yhvAexrWvpDz+Y2/5C8XOjxtI0Kkfy5HO/H3F0aFdbTCSCS8hUeHZglxY9/Fjwwzz0HputDUzHVmuPC4e2JZ9xeUDaeNpAh+t/SnbdoMf9l+wRo6QR+10r4nk6zewJw7ihvpqHahcDQoV/ACI/Y9SDaP7EC44yDsYQ=
after_success: 
before_deploy: 
